export CONDA_BACKUP_OCL_ICD_FILENAMES="${OCL_ICD_FILENAMES}:-"
export OCL_ICD_FILENAMES=libintelocl.so

export CONDA_BACKUP_SYCL_ENABLE_HOST_DEVICE="${SYCL_ENABLE_HOST_DEVICE}:-"
export SYCL_ENABLE_HOST_DEVICE=1

export CONDA_BACKUP_LD_PRELOAD="${LD_PRELOAD}:-"
export LD_PRELOAD=$CONDA_PREFIX/lib/libOpenCL.so:${LD_PRELOAD}