export OCL_ICD_FILENAMES="${CONDA_BACKUP_OCL_ICD_FILENAMES}"
unset CONDA_BACKUP_OCL_ICD_FILENAMES
if [[ -z ${OCL_ICD_FILENAMES} ]]; then
  unset OCL_ICD_FILENAMES
fi

export SYCL_ENABLE_HOST_DEVICE="${CONDA_BACKUP_SYCL_ENABLE_HOST_DEVICE}"
unset CONDA_BACKUP_SYCL_ENABLE_HOST_DEVICE
if [[ -z ${SYCL_ENABLE_HOST_DEVICE} ]]; then
  unset SYCL_ENABLE_HOST_DEVICE
fi

export LD_PRELOAD="${CONDA_BACKUP_LD_PRELOAD}"
unset CONDA_BACKUP_LD_PRELOAD
if [[ -z ${LD_PRELOAD} ]]; then
  unset LD_PRELOAD
fi